export const ApiErrorCode = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',

  // Server Errors
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  SERVER_ALREADY_EXISTS: 'SERVER_ALREADY_EXISTS',
  SERVER_ALREADY_RUNNING: 'SERVER_ALREADY_RUNNING',
  SERVER_NOT_RUNNING: 'SERVER_NOT_RUNNING',
  SERVER_SUSPENDED: 'SERVER_SUSPENDED',
  SERVER_INSUFFICIENT_MEMORY: 'SERVER_INSUFFICIENT_MEMORY',
  SERVER_INSUFFICIENT_DISK: 'SERVER_INSUFFICIENT_DISK',
  SERVER_INSUFFICIENT_CPU: 'SERVER_INSUFFICIENT_CPU',
  SERVER_INSTALLING: 'SERVER_INSTALLING',
  SERVER_POWER_ACTION_FAILED: 'SERVER_POWER_ACTION_FAILED',

  // Node Errors
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',
  NODE_OFFLINE: 'NODE_OFFLINE',
  NODE_UNREACHABLE: 'NODE_UNREACHABLE',
  NODE_MAINTENANCE: 'NODE_MAINTENANCE',
  NODE_INSUFFICIENT_RESOURCES: 'NODE_INSUFFICIENT_RESOURCES',

  // Allocation Errors
  ALLOCATION_NOT_FOUND: 'ALLOCATION_NOT_FOUND',
  ALLOCATION_ALREADY_ASSIGNED: 'ALLOCATION_ALREADY_ASSIGNED',
  ALLOCATION_NOT_AVAILABLE: 'ALLOCATION_NOT_AVAILABLE',

  // Blueprint / Egg Errors
  BLUEPRINT_NOT_FOUND: 'BLUEPRINT_NOT_FOUND',
  BLUEPRINT_INVALID_SCHEMA: 'BLUEPRINT_INVALID_SCHEMA',
  BLUEPRINT_PARSER_ERROR: 'BLUEPRINT_PARSER_ERROR',

  // Module Errors
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_ALREADY_INSTALLED: 'MODULE_ALREADY_INSTALLED',
  MODULE_ENABLE_FAILED: 'MODULE_ENABLE_FAILED',
  MODULE_DEPENDENCY_MISSING: 'MODULE_DEPENDENCY_MISSING',

  // File System Errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_PERMISSION_DENIED: 'FILE_PERMISSION_DENIED',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',

  // Generic System Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export interface ApiErrorDetail {
  code: ApiErrorCode | string;
  message?: string;
  params?: Record<string, unknown>;
}

export interface ApiErrorResponse {
  success: false;
  error: ApiErrorDetail;
}

export interface ApiSuccessResponse<T> {
  success: true;
  data: T;
  meta?: Record<string, unknown>;
}

export type ApiResponse<T> = ApiSuccessResponse<T> | ApiErrorResponse;
